### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by MuKwang** [vthinsel/GT7Proxy#2]
Create an exe file and run it, the following error occurs.

Traceback (most recent call last):
  File "GT7Proxy.py", line 15, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "salsa20.py", line 18, in <module>
  File "imp.py", line 296, in find_module
ImportError: No module named '_salsa20'
[36440] Failed to execute script 'GT7Proxy' due to unhandled exception!

I checked that it is executed in py file.

I tried various ways, but I couldn't solve it. Please help me. OTL...

**Comment by MuKwang** [comment]
The cause has been found.

_salsa20.cp39-win_amd64.pyd 

The error occurred because this file was not included.

After compiling without using the spec file, copy and run the above file in the dist folder, and it runs normally.

The funny thing is, after doing that, when I compile it back into a spec file, it runs normally. 

What the...
